### ISSUE TITLE
Error for using illegal functions when none are present

### ISSUE THREAD

**Issue by mattrjones** [learn-co-curriculum/programming-univbasics-4-square-array#3]
I'm getting an error message for my code saying that it does not meet the requirement for not using map, each, inject, et al., but none of those are present in my code

**Comment by sgharms** [comment]
I took a look at your code in https://github.com/Red-Trinket/programming-univbasics-4-square-array-online-web-prework

Your final commit works and seems to pass our tests. The tests look properly constructed:

```ruby
    numbers = [1,2,3]
    expect(numbers).to_not receive(:each)
    expect(numbers).to_not receive(:collect)
    expect(numbers).to_not receive(:map)
    expect(numbers).to_not receive(:inject)
    square_array(numbers)
  end
```

and I wouldn't expect your code to trigger them to fail. Is this still a problem?

**Comment by sgharms** [comment]
Hey @Red-Trinket, since we haven't heard back we're going to close this issue. Please re-open if it's still not working for you.
